name = "zephyr-soroban-op-ratio"

[[tables]]
name = "opratio"

[[tables.columns]]
name = "sequence"
col_type = "BYTEA"

[[tables.columns]]
name = "soroban"
col_type = "BYTEA"

[[tables.columns]]
name = "ratio"
col_type = "BYTEA"
